apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.fullname" . }}-auth
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
stringData:
  gemini-api-key: {{ .Values.env.geminiApiKey | quote }}
